# Generated by Django 5.1.6 on 2026-06-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OduncAlmaSistemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aldigiTarih', models.DateField(auto_now_add=True)),
                ('verecegi_tarih', models.DateField()),
                ('teslim_edildi', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.bookinfo')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.bookcategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userinfo')),
            ],
        ),
    ]
