# Generated by Django 5.1.6 on 2026-06-05 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookInfo', '0006_bookinfo_book_slug'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OduncAlmaSistemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aldigiTarih', models.DateField(auto_now_add=True)),
                ('verecegi_tarih', models.DateField()),
                ('teslim_edildi', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookInfo.bookinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userinfo')),
            ],
        ),
    ]
