# Generated by Django 5.1.6 on 2026-06-05 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0006_bookinfo_book_slug'),
        ('OduncAlmaSistemi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oduncalmasistemi',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BookInfo.bookcategori'),
            preserve_default=False,
        ),
    ]
