# Generated by Django 5.1.6 on 2026-06-10 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookCategori', '0001_initial'),
        ('OduncAlmaSistemi', '0002_oduncalmasistemi_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oduncalmasistemi',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookCategori.bookcategori'),
        ),
    ]
