# Generated by Django 5.1.6 on 2026-07-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OduncAlmaSistemi', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oduncalmasistemi',
            name='teslim_edildi',
        ),
        migrations.AddField(
            model_name='oduncalmasistemi',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('borrowed', 'Kullanıcıda'), ('returned', 'İade Edildi'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20),
        ),
    ]
