# Generated by Django 5.1.6 on 2026-06-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_categori', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categori_isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
