# Generated by Django 5.1.6 on 2026-05-23 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_categori', models.CharField(max_length=100)),
                ('categori_isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=12, unique=True)),
                ('price', models.FloatField()),
                ('writer', models.CharField(max_length=70)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookInfo.bookcategori')),
            ],
        ),
    ]
