# Generated by Django 5.1.6 on 2026-05-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategori',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
