# Generated by Django 5.1.6 on 2026-05-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0002_bookcategori_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategori',
            name='slug',
            field=models.SlugField(blank=True, default='empty', unique=True),
        ),
    ]
