# Generated by Django 5.1.6 on 2026-05-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0003_alter_bookcategori_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategori',
            name='slug',
        ),
        migrations.AddField(
            model_name='bookcategori',
            name='new_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
