# Generated by Django 5.1.6 on 2026-05-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0004_remove_bookcategori_slug_bookcategori_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategori',
            name='new_field',
        ),
        migrations.AddField(
            model_name='bookcategori',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
