# Generated by Django 5.1.6 on 2026-06-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0005_remove_bookcategori_new_field_bookcategori_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='book_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
