# Generated by Django 5.1.6 on 2026-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0006_bookinfo_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
