# Generated by Django 5.1.6 on 2026-06-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0007_bookinfo_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='stock',
        ),
    ]
