# Generated by Django 5.1.6 on 2026-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0008_remove_bookinfo_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
