# Generated by Django 5.1.6 on 2026-06-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0010_alter_bookinfo_kategori_delete_bookcategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='stock',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
