# Generated by Django 5.1.6 on 2026-06-12 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0011_bookinfo_stock'),
        ('WriterBook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='writer',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='writer_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WriterBook.writer'),
            preserve_default=False,
        ),
    ]
