# Generated by Django 5.1.6 on 2026-07-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_categori', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categori_isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategori_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_categori', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categori_isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=25)),
                ('lang', models.CharField(db_index=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('isActive', models.BooleanField(default=True)),
                ('dateAdd', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_slug', models.SlugField(blank=True, unique=True)),
                ('barcode', models.CharField(max_length=12, unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, default=1)),
                ('isActive', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.bookcategori')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Book.booklanguage')),
                ('writer_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.writer')),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='Book_image/')),
                ('isActive', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Book.bookinfo')),
            ],
        ),
    ]
