# Generated by Django 5.1.6 on 2026-06-21 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='Book_image/')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='Image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book.bookimage'),
            preserve_default=False,
        ),
    ]
