# Generated by Django 5.1.6 on 2026-06-21 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_bookimage_bookinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='Image',
        ),
        migrations.AddField(
            model_name='bookimage',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Book.bookinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='resim',
            field=models.ImageField(default=1, upload_to='Book_image/'),
            preserve_default=False,
        ),
    ]
