# Generated by Django 5.1.6 on 2026-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_remove_bookinfo_image_bookimage_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
