# Generated by Django 5.1.6 on 2026-06-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_userinfo_options_alter_userinfo_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'user')], default='user', max_length=20),
        ),
    ]
