# Generated by Django 5.1.6 on 2026-07-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Bekliyor'), ('ready', 'Hazır'), ('cancelled', 'İptal'), ('completed', 'Tamamlandı')], default='waiting', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.bookinfo')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
